const locations = [

{
id:1,
name:"Дулаг-130",
years:["1941","1942","1943"],
date:"1941–1943",
place:"Рославль, Смоленская область",
type:"Лагерь военнопленных (Dulag)",
victims:"≈30 000",
description:"Пересыльный лагерь для советских военнопленных.",
archive:"https://pamyat-naroda.ru/",
image:"https://upload.wikimedia.org/wikipedia/commons/3/3e/Roslavl_ww2.jpg",
more:"Смертность от голода, болезней и расстрелов. Заключённые содержались под открытым небом.",
lat:53.952,
lng:32.860,
color:"yellow"
},

{
id:2,
name:"Армейский сборный пункт №202",
years:["1941","1942"],
date:"1941–1942",
place:"Брянск",
type:"Сборный пункт военнопленных",
victims:"Неизвестно",
description:"Сбор и распределение советских военнопленных.",
archive:"https://pamyat-naroda.ru/",
image:"https://upload.wikimedia.org/wikipedia/commons/5/5f/Bryansk_ww2.jpg",
more:"Военнопленные направлялись в лагеря Германии и Польши.",
lat:53.242,
lng:34.365,
color:"yellow"
},

{
id:3,
name:"Малый Тростенец",
years:["1941","1942","1943","1944"],
date:"1941–1944",
place:"Минск, Беларусь",
type:"Концентрационный лагерь",
victims:"≈60 000+",
description:"Крупнейший лагерь уничтожения на территории Беларуси.",
archive:"https://www.yadvashem.org/",
image:"https://upload.wikimedia.org/wikipedia/commons/5/5f/Maly_Trostenets_memorial.jpg",
more:"Уничтожение в газовых машинах и массовые расстрелы.",
lat:53.840,
lng:27.690,
color:"red"
},

{
id:4,
name:"Саласпилс",
years:["1941","1942","1943","1944"],
date:"1941–1944",
place:"Саласпилс, Латвия",
type:"Концентрационный лагерь",
victims:"≈12 000",
description:"Лагерь содержания взрослых и детей.",
archive:"https://www.ushmm.org/",
image:"https://upload.wikimedia.org/wikipedia/commons/0/08/Salaspils_memorial.jpg",
more:"Использовался как трудовой и транзитный лагерь.",
lat:56.860,
lng:24.350,
color:"red"
},

{
id:5,
name:"Шталаг-352",
years:["1941","1942","1943","1944"],
date:"1941–1944",
place:"Масюковщина (Минск)",
type:"Лагерь военнопленных",
victims:"≈80 000",
description:"Крупный лагерь для советских военнопленных.",
archive:"https://pamyat-naroda.ru/",
image:"https://upload.wikimedia.org/wikipedia/commons/a/a6/Stalag_352_memorial.jpg",
more:"Массовая гибель от истощения и болезней.",
lat:53.940,
lng:27.450,
color:"yellow"
},

{
id:6,
name:"Шталаг 1-Д",
years:["1941","1942","1943"],
date:"1941–1943",
place:"Пригородное",
type:"Лагерь военнопленных",
victims:"Неизвестно",
description:"Лагерь для военнопленных.",
archive:"https://pamyat-naroda.ru/",
image:"https://upload.wikimedia.org/wikipedia/commons/4/4f/Stalag.jpg",
more:"Использовался для временного содержания.",
lat:54.000,
lng:22.000,
color:"yellow"
},

{
id:7,
name:"Дулаг-142",
years:["1941","1942"],
date:"1941–1942",
place:"Брянск",
type:"Лагерь военнопленных (Dulag)",
victims:"Неизвестно",
description:"Пересыльный лагерь.",
archive:"https://pamyat-naroda.ru/",
image:"https://upload.wikimedia.org/wikipedia/commons/2/22/WW2_camp.jpg",
more:"Военнопленные направлялись далее в Германию.",
lat:53.242,
lng:34.365,
color:"yellow"
},

{
id:8,
name:"Дулаг-205",
years:["1942","1943"],
date:"1942–1943",
place:"Алексеевка",
type:"Лагерь военнопленных",
victims:"Неизвестно",
description:"Пересыльный лагерь.",
archive:"https://pamyat-naroda.ru/",
image:"https://upload.wikimedia.org/wikipedia/commons/2/22/WW2_camp.jpg",
more:"Функционировал в разные годы в разных местах.",
lat:50.630,
lng:38.690,
color:"yellow"
},

{
id:9,
name:"Яновский лагерь",
years:["1941","1942","1943","1944"],
date:"1941–1944",
place:"Львов, Украина",
type:"Концентрационный лагерь",
victims:"≈40 000",
description:"Лагерь принудительного труда.",
archive:"https://www.yadvashem.org/",
image:"https://upload.wikimedia.org/wikipedia/commons/7/77/Lviv_Janowska.jpg",
more:"Место массовых казней.",
lat:49.850,
lng:24.000,
color:"red"
},

{
id:10,
name:"Детский лагерь Вырица",
years:["1942","1943"],
date:"1942–1943",
place:"Вырица, Ленинградская область",
type:"Детский концлагерь",
victims:"Сотни детей",
description:"Лагерь для детей.",
archive:"https://pamyat-naroda.ru/",
image:"https://upload.wikimedia.org/wikipedia/commons/6/6f/Children_WW2.jpg",
more:"Дети использовались для принудительных работ.",
lat:59.420,
lng:30.350,
color:"purple"
},

{
id:11,
name:"Майданек",
years:["1941","1942","1943","1944"],
date:"1941–1944",
place:"Люблин, Польша",
type:"Концентрационный лагерь",
victims:"≈78 000",
description:"Лагерь уничтожения.",
archive:"https://www.majdanek.eu/",
image:"https://upload.wikimedia.org/wikipedia/commons/4/4f/Majdanek.jpg",
more:"Газовые камеры и расстрелы.",
lat:51.250,
lng:22.570,
color:"red"
},

{
id:12,
name:"Сырецкий лагерь",
years:["1942","1943"],
date:"1942–1943",
place:"Киев, Украина",
type:"Концентрационный лагерь",
victims:"Тысячи",
description:"Лагерь рядом с Бабьим Яром.",
archive:"https://www.ushmm.org/",
image:"https://upload.wikimedia.org/wikipedia/commons/0/0e/Babi_Yar_memorial.jpg",
more:"Заключённые использовались для сокрытия следов преступлений.",
lat:50.470,
lng:30.450,
color:"red"
},

{
id:13,
name:"Богдановка",
years:["1941","1942"],
date:"1941–1942",
place:"Николаевская область, Украина",
type:"Массовое уничтожение",
victims:"≈40 000",
description:"Место массового уничтожения евреев.",
archive:"https://www.yadvashem.org/",
image:"https://upload.wikimedia.org/wikipedia/commons/3/3e/Mass_grave.jpg",
more:"Расстрелы и сожжение людей.",
lat:47.200,
lng:31.300,
color:"black"
},

{
id:14,
name:"Бабий Яр",
years:["1941"],
date:"29–30 сентября 1941",
place:"Киев, Украина",
type:"Массовый расстрел",
victims:"≈33 000",
description:"Массовое уничтожение евреев Киева.",
archive:"https://www.ushmm.org/",
image:"https://upload.wikimedia.org/wikipedia/commons/0/0e/Babi_Yar_memorial.jpg",
more:"Одно из крупнейших преступлений Холокоста.",
lat:50.470,
lng:30.450,
color:"black"
},

{
id:15,
name:"Змиёвская балка",
years:["1942"],
date:"Август 1942",
place:"Ростов-на-Дону",
type:"Массовый расстрел",
victims:"≈27 000",
description:"Место уничтожения евреев.",
archive:"https://www.ushmm.org/",
image:"https://upload.wikimedia.org/wikipedia/commons/3/3f/Zmievskaya_Balka.jpg",
more:"Крупнейшее место расстрела на территории РФ.",
lat:47.240,
lng:39.630,
color:"black"
},

{
id:16,
name:"Концлагерь «Красный» (Dulag 241)",
years:["1942","1943","1944"],
date:"1942–1944",
place:"Крым",
type:"Концентрационный лагерь",
victims:"Тысячи",
description:"Лагерь уничтожения.",
archive:"https://pamyat-naroda.ru/",
image:"https://upload.wikimedia.org/wikipedia/commons/2/22/WW2_camp.jpg",
more:"Массовые казни и истощение.",
lat:44.950,
lng:34.100,
color:"red"
},

{
id:17,
name:"Жестяная Горка",
years:["1941","1942","1943"],
date:"1941–1943",
place:"Новгородская область",
type:"Массовые убийства",
victims:"≈2 600",
description:"Место массовых расстрелов.",
archive:"https://pamyat-naroda.ru/",
image:"https://upload.wikimedia.org/wikipedia/commons/3/3e/Mass_grave.jpg",
more:"Обнаружены массовые захоронения.",
lat:58.650,
lng:30.300,
color:"black"
},

{
id:18,
name:"Корюковская трагедия",
years:["1943"],
date:"1–2 марта 1943",
place:"Корюковка, Украина",
type:"Сожжение населённого пункта",
victims:"≈6 700",
description:"Уничтожение города.",
archive:"https://pamyat-naroda.ru/",
image:"https://upload.wikimedia.org/wikipedia/commons/6/6b/Khatyn_memorial.jpg",
more:"Одна из крупнейших карательных акций.",
lat:51.770,
lng:32.250,
color:"black"
},

{
id:19,
name:"Хатынь",
years:["1943"],
date:"22 марта 1943",
place:"Минская область, Беларусь",
type:"Сожжение деревни",
victims:"149",
description:"Деревня уничтожена карателями.",
archive:"https://pamyat-naroda.ru/",
image:"https://upload.wikimedia.org/wikipedia/commons/6/6b/Khatyn_memorial.jpg",
more:"Жители были сожжены заживо.",
lat:54.330,
lng:27.870,
color:"black"
},

{
id:20,
name:"Колдычево",
years:["1942","1943","1944"],
date:"1942–1944",
place:"Брестская область, Беларусь",
type:"Концентрационный лагерь",
victims:"≈22 000",
description:"Лагерь уничтожения возле Колдычево.",
archive:"https://pamyat-naroda.ru/",
image:"https://upload.wikimedia.org/wikipedia/commons/0/0a/Koldychevo_memorial.jpg",
more:"Расстрелы и газовые машины.",
lat:53.150,
lng:25.980,
color:"red"
}

];
